services:
  pointer:
    image: 'pointer:latest'
    ports:
      - 3301:80
    volumes:
      - ./appsettings.json:/app/appsettings.json
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data/

volumes:
  postgres: